"""empty message

Revision ID: 58d9b3cf9400
Revises: 
Create Date: 2019-10-24 09:33:33.356048

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '58d9b3cf9400'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    op.execute("delete from users")
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'users', ['username'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    # ### end Alembic commands ###
