"""empty message

Revision ID: bd9534f3e9e8
Revises: 0b2308c031e4
Create Date: 2019-10-24 22:37:45.708883

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bd9534f3e9e8'
down_revision = '0b2308c031e4'
branch_labels = None
depends_on = None


def upgrade():
    op.execute("delete from users")
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('password', sa.String(length=1024), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'password')
    # ### end Alembic commands ###
